### ISSUE TITLE
Tyler: Add assets for team presentation

### ISSUE THREAD

**Issue by IascAtBrock** [IascAtBrock/IASC-2P02-TeamPresentations#1]
This is an individual issue assigned to you alone. Mark it as resolved once you have finished uploading your assets to your team's shared fork.

**Comment by TylerJBourg** [comment]
How it was funded ?(Tyler) .
-          Began in 1995 at Brown University, started using funds from the university and small local grants
-          First major project was a digital edition of The New Age which was a British weekly magazine that was edited by A.R. Orage from 1907- 1922
-          Was completed with aid from a grant from the National Endowment for the Humanities
-          Three More Grants would be made by the NEH one in the 2008-2009 academic year and another during the 2010-2011 academic year and one in the spring of 2012 

Where is it located (what universities, organizations, etc.)?
-          Brown University (1995)
-          University of Tulsa (2003)
The Modernist Journals Project (searchable database). Brown and Tulsa Universities, ongoing. http://www.modjourn.org

https://yt3.ggpht.com/a-/AAuE7mBPWJTDQWcamYwnyxSPWNim4GdMgqyOHYjtmA=s900-mo-c-c0xffffffff-rj-k-no 

https://specials-images.forbesimg.com/imageserve/55ae612fe4b05c2c34321222/300x300.jpg?fit=scale&background=000000

**Comment by TylerJBourg** [comment]
![1](https://user-images.githubusercontent.com/31972335/52462084-9a1c7100-2b3f-11e9-87b6-4b726ba2ba9f.png)

**Comment by TylerJBourg** [comment]
![2](https://user-images.githubusercontent.com/31972335/52462207-2333a800-2b40-11e9-81ef-cbf96048aba3.png)
![3](https://user-images.githubusercontent.com/31972335/52462210-24fd6b80-2b40-11e9-899e-0a25035bf35f.png)
![4](https://user-images.githubusercontent.com/31972335/52462213-26c72f00-2b40-11e9-9c4b-d95db2906cc3.png)
![5](https://user-images.githubusercontent.com/31972335/52462217-2890f280-2b40-11e9-89b5-c89361f30b18.png)
![6](https://user-images.githubusercontent.com/31972335/52462219-29c21f80-2b40-11e9-926b-0fb50b5e1857.png)

**Comment by TylerJBourg** [comment]
Who works on the project?

Director at Brown is  Susan Smulya 
Director at Tulsa is Jeff Drouin
Technical advisor for the MJP is Clifford Wulfman 
Project manager for the MJP is Mark Gaipa 
Then there is a team of advisors who are consulted about what projects should be pursued
Their is also a Brown and Tusula specific advisory board

**Comment by TylerJBourg** [comment]
Updated powerpoint 
[Modernist Journals Project.pptx](https://github.com/IascAtBrock/IASC-2P02-TeamPresentations/files/2846641/Modernist.Journals.Project.pptx)
