### ISSUE TITLE
Josh: Add assets for team presentation

### ISSUE THREAD

**Issue by IascAtBrock** [IascAtBrock/IASC-2P02-TeamPresentations#18]
This is an individual issue assigned to you alone. Mark it as resolved once you have finished uploading your assets to your team's shared fork.

**Comment by JoshuaYDucharme-Baribeau** [comment]
Scalar Project: https://scalar.usc.edu/works/iasc-2p02-engagement
Slides of the presentation I created:
[Josh's slides for IASC 2P02 ASGNT 1.pdf](https://github.com/IascAtBrock/IASC-2P02-TeamPresentations/files/4145633/Josh.s.slides.for.IASC.2P02.ASGNT.1.pdf)
