### ISSUE TITLE
Justin: Add assets for team presentation

### ISSUE THREAD

**Issue by IascAtBrock** [IascAtBrock/IASC-2P02-TeamPresentations#18]
This is an individual issue assigned to you alone. Mark it as resolved once you have finished uploading your assets to your team's shared fork.

**Comment by JustinCo13** [comment]
This issue is resolved!

**Comment by JustinCo13** [comment]
[IASC_2P02_PRESENTATION_OVERVIEW.docx](https://github.com/IascAtBrock/IASC-2P02-TeamPresentations/files/1701195/IASC_2P02_PRESENTATION_OVERVIEW.docx)
