### ISSUE TITLE
Diane: Add assets for team presentation

### ISSUE THREAD

**Issue by IascAtBrock** [IascAtBrock/IASC-2P02-TeamPresentations#21]
This is an individual issue assigned to you alone. Mark it as resolved once you have finished uploading your assets to your team's shared fork.

**Comment by DianeKohler007** [comment]
**Aloha**

**Comment by DianeKohler007** [comment]
**Aloha**

[http://serendip-o-matic.com/](url)

**Comment by DianeKohler007** [comment]
https://docs.google.com/presentation/d/1CBxrGmrTmkwI7rqamOQ-Vnj7nSiVH-CmNKFgsMhT0ZA/edit?usp=sharing
