### ISSUE TITLE
Eugene: Add assets for team presentation

### ISSUE THREAD

**Issue by IascAtBrock** [IascAtBrock/IASC-2P02-TeamPresentations#24]
This is an individual issue assigned to you alone. Mark it as resolved once you have finished uploading your assets to your team's shared fork.

**Comment by meangene75** [comment]
All assets finished 
https://docs.google.com/presentation/d/1SBUiR8eH056NrE1A72K6NGf_LAbTeC8sVg6N3V2dShE/edit?usp=drivesdk 

https://docs.google.com/document/d/1fKP-EzgF6fhKmTEPfUHGM-1I03p_ruYMmQXUXftnrfk/edit?usp=drivesdk
