### ISSUE TITLE
Reymar: Add assets for team presentation

### ISSUE THREAD

**Issue by IascAtBrock** [IascAtBrock/IASC-2P02-TeamPresentations#35]
This is an individual issue assigned to you alone. Mark it as resolved once you have finished uploading your assets to your team's shared fork.

**Comment by ReyLibra** [comment]
[StoryMapJS.pdf](https://github.com/IascAtBrock/IASC-2P02-TeamPresentations/files/4146080/StoryMapJS.pdf)
![IASC2P02-Assignment01-img01](https://user-images.githubusercontent.com/55162735/73622659-05d8d300-4608-11ea-94af-316aff437558.png)
![IASC2P02-Assignment01-img02](https://user-images.githubusercontent.com/55162735/73622662-070a0000-4608-11ea-9999-f9285223cfd5.png)
![IASC2P02-Assignment01-img03](https://user-images.githubusercontent.com/55162735/73622664-083b2d00-4608-11ea-8488-f396ccec9f94.png)
![IASC2P02-Assignment01-img04](https://user-images.githubusercontent.com/55162735/73622667-0bceb400-4608-11ea-99ed-ac010c98d20a.png)
![IASC2P02-Assignment01-img05](https://user-images.githubusercontent.com/55162735/73622669-0e310e00-4608-11ea-9429-fc4ad244edad.png)
